name: Build CLI App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up GCC and Make
      run: |
        if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
          sudo apt-get update
          sudo apt-get install -y gcc make
        elif [ ${{ matrix.os }} == 'macos-latest' ]; then
          brew install gcc make
        elif [ ${{ matrix.os }} == 'windows-latest' ]; then
          choco install mingw
        fi

    - name: Build
      run: |
        make
      shell: bash

    - name: Verify Binary
      run: |
        file build/calc
      shell: bash

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        RELEASE_TAG=$(date +'%Y-%m-%d')
        echo "Creating release $RELEASE_TAG"
        
        # Create a release on GitHub
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"tag_name": "'"$RELEASE_TAG"'","name": "'"$RELEASE_TAG"'","body": "Automated release of calc binaries."}' \
          "https://api.github.com/repos/${{ github.repository }}/releases"

    - name: Upload Binaries to Release
      run: |
        BUILD_DATE=$(date +'%Y-%m-%d')  # Same format for filename
        
        if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
          FILENAME="calc-linux-x86_64-${BUILD_DATE}.zip"
          zip -r $FILENAME build/calc
        elif [ ${{ matrix.os }} == 'macos-latest' ]; then
          FILENAME="calc-macos-x86_64-${BUILD_DATE}.zip"
          zip -r $FILENAME build/calc
        elif [ ${{ matrix.os }} == 'windows-latest' ]; then
          FILENAME="calc-win-x86_64-${BUILD_DATE}.zip"
          zip -r $FILENAME build/calc.exe
        fi

        # Upload the binary zip file to the release
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/zip" \
          --data-binary @$FILENAME \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.id }}/assets?name=$FILENAME"
